

const variants = (names, prices) => names.map((name, i) => ({ name, price: prices[i] }));
const proteins = ['Bio-Tofu', 'Huhn (gebraten)', 'Huhn (gebacken)', 'Ente (knusprig)', 'Garnelen'];
export const menuCategories = ['Alle', 'Mittagsangebot', 'Salate & Sommerrollen', 'Suppen', 'Reis & Wok', 'Nudeln & Bowls', 'Sushi', 'Desserts', 'Getränke'];
// Transcribed from the supplied recording. Missing prices remain unset; lunch is separate.
export const menuGroups = [
 { title: 'Mittagsangebot', category: 'Mittagsangebot', items: [
  {name:'Miso-Soup',price:3.5,description:'Sojabohnenpaste, Seetang, Seidentofu, Frühlingszwiebeln'},
  {name:'Wantan Soup',price:5,description:'Hühnerfleisch, Garnelen, Austernpilze, Hühnerbrühe, Pak Choi'},
  {name:'Fit And Fun Salad',price:5.5,description:'Salat, Gurke, Avocado, Tomaten, Mango, Erdnüsse, Dressing'},
  {name:'Spring Rolls',price:5.5,description:'3 Stück · Hühnerei, Karotten, Pilze, Pfeffer, Zwiebeln, Erdnüsse'},
  {name:'Mini Frühlingsrolle',price:5,description:'Süß-Sauer-Soße · vegetarisch'},
  {name:'Chicken Skewers',price:5.5,description:'2 Hühnerspieße · Sesam und Erdnusssoße'},
  {name:'Curry mit Tofu',price:10,description:'Rotes Curry, Kokosmilch, Sahne, Gemüse, Milch'},
  {name:'Mango mit Huhn gebraten',price:11,description:'Mangosoße, Milch, Kokosmilch, Sahne, Gemüse'},
  {name:'Erdnuss mit Huhn gebacken',price:12,description:'Erdnusssoße, Milch, frisches Gemüse, Duftreis'},
  {name:'Gemüse-Wok mit Ente',price:13.9,description:'Dunkle Soße, Gemüse, Reis'},
  {name:'Udon mit Rinderfilet',price:13,description:'Japanische Udon-Nudeln, Gemüse, Rinderfilet'},
  {name:'Pho Ha Noi mit Rindfleisch',price:13,description:'Reisbandnudelsuppe, Lauchzwiebeln, Mungosprossen, Koriander'},
  {name:'Pho Xao mit Hühnerfleisch',price:12,description:'Gebratene Reisbandnudeln, Ei, Gemüse, Lauchzwiebeln, Koriander, Mungosprossen, Röstzwiebeln'},
  {name:'Sushi Platte · Lachs',price:12.9,description:'2 Sake Nigiri, 6 Avocado Maki, 6 Tobiko Dream (gebacken)'},
  {name:'Sushi Platte · Mix',price:15,description:'2 Avocado Nigiri, 8 Sake Inside Out, 6 Lucky Lady Thunfisch'},
  {name:'Sushi Platte Vegetarian',price:12.9},
 ]},
 {title:'Salate',category:'Salate & Sommerrollen',items:[
  {name:'Seetang-Salad',price:6.5,description:'Tomate, Sesam'},
  {name:'Fit And Fun Salad',price:6.8,description:'Salat, Gurke, Avocado, Tomaten, Mango, Erdnüsse, Dressing'},
  {name:'Beef Salad',price:10,description:'Salat, Gurke, Avocado, Tomaten, Mango, Rinderfiletstreifen, Erdnüsse, Dressing'},
  {name:'Mizu Prawns Salad',price:10,description:'Salat, Mango, Gurke, Avocado, Tomaten, Garnelen, Erdnüsse, Dressing'},
  {name:'Kimchi-Salad',price:5,description:'Eingelegter Chinakohl, Karotten, Sesam'},
  {name:'Lachs Tataki',price:16.8,description:'Wildlachs, Avocado, Gurke, Wildkräuter'},
 ]},
 {title:'Fresh Sommerrollen',category:'Salate & Sommerrollen',description:'Reisnudeln, Salat, Sesam und Erdnüsse',items:variants(['Bio-Tofu','Garnelen','Hühnerfleisch','Avocado'],[5.5,6.9,6.9,5.5])},
 {title:'Mizu Suppen',category:'Suppen',items:[
  {name:'Miso-Soup',price:4,description:'Sojabohnenpaste, Seetang, Seidentofu, Frühlingszwiebeln'},
  {name:'Wantan Soup',price:6.5,description:'Hühnerfleisch, Garnelen, Austernpilze, klare Hühnerbrühe, Pak Choi, Frühlingszwiebeln'},
 ]},
 {title:'Mr. Tokio Suppe',category:'Suppen',description:'Kokosmilch, Galgant, Austernpilze, Zwiebeln, Cherrytomaten, Seetang, Limettenblätter',items:variants(['Bio-Tofu','Huhn','Garnelen'],[5.5,6.5,8])},
 {title:'Mango-Jasmin Reis',category:'Reis & Wok',description:'Mangosoße, Milch, frisches Gemüse und Duftreis',items:variants(proteins,[12,13,14,17,20])},
 {title:'Erdnuss Cream',category:'Reis & Wok',description:'Erdnusssoße, Milch, frisches Gemüse und Duftreis',items:variants(proteins,[12,13,14,17,20])},
 {title:'Gemüse-Wok',category:'Reis & Wok',description:'Dunkle Soße, Gemüse und Jasminreis',items:variants(proteins,[12,13,14,17,20])},
 {title:'Mizu-Spezial mit Reis',category:'Reis & Wok',items:[
  {name:'Wild Dorade',price:22,description:'Wildfang-Dorade, Frühlingszwiebeln, Dill, Tomatensoße, Jasminreis'},
  {name:'Salmon Teriyaki',price:20,description:'Schottischer Lachs, Teriyaki-Soße, Gemüse, Dill, Frühlingszwiebeln, Jasminreis, Sesam'},
  {name:'Mizu King-Prawns',price:26,description:'Garnelen, Spezialsoße des Hauses, Bratgemüse, Jasminreis oder Süßkartoffelstreifen'},
  {name:'Beef Special',price:18,description:'Rinderfiletstreifen, Knoblauch, Zitronengras, Gemüse, Jasminreis'},
 ]},
 {title:'Hauptgerichte',category:'Reis & Wok',items:[
  {name:'Beef-Special',price:13.8,description:'Rinderfilet, Knoblauch, Zwiebeln, Paprika, Sesam'},
  {name:'Tofu Tomatoes',price:13.8,description:'Tofu mit Saisongemüse'},
  {name:'VIP Reis Wok',price:22,description:'Gebratener Reis, Tofu, Karotten, Rinderfilet, Garnelen, Kimchi, Zwiebeln'},
 ]},
 {title:'Dunkle Soße mit Jasminreis',category:'Reis & Wok',description:'Dunkle Soße mit Gemüse',items:variants(['Bio-Tofu','Hühnerfleisch','Hühnerfleisch gebacken','Ente kross','Garnelen'],[12,12.9,13.9,16.9,18])},
 {title:'Gebratener Reis',category:'Reis & Wok',items:variants(['Hühnerfleisch','Hühnerfleisch gebacken','Ente kross','Garnelen'],[12,12.9,16,16])},
 {title:'Bun Nam Bo',category:'Nudeln & Bowls',description:'Reisnudelsalat mit Kräutern, Erdnüssen und Sesamdressing',items:variants(['Bio-Tofu','Huhn (gebraten)','Frühlingsrolle Chicken','Rinderfilet'],[12,14,15,17])},
 {title:'Pho Ha Noi',category:'Nudeln & Bowls',description:'Reisbandnudelsuppe in hausgemachter Brühe mit Lauchzwiebeln, Mungosprossen und Koriander',items:variants(['Bio-Tofu','Hühnerfleisch','Rindfleisch'],[13,15,16])},
 {title:'Donburi / Bowl',category:'Nudeln & Bowls',description:'Sushireis, Salat, eingelegter Ingwer, Sesam und Spezialsoße',items:variants(['Seidentofu','Rinderfilet','Hühnerfleisch','Lachs Bowl'],[12.9,18,15,22])},
 {title:'Udon Noodles Wok',category:'Nudeln & Bowls',description:'Gebratene Udon-Nudeln mit Gemüse und Frühlingszwiebeln',items:variants(['Bio-Tofu','Hühnerfleisch','Rinderfilet','Garnelen','Ente kross'],[12,13.9,16,16,16])},
 {title:'Sashimi',category:'Sushi',items:[
  {name:'Sake Sashimi',price:12.5,description:'5 Scheiben roher Lachs'},
  {name:'Tuna Sashimi',price:12.5,description:'5 Scheiben roher Thunfisch'},
  {name:'Ebi Sashimi',price:12,description:'5 gekochte Garnelen'},
  {name:'The Mix Sashimi',price:22.5,description:'3 Lachs, 3 Thunfisch, 3 Garnelen'},
 ]},
 {title:'Sushi Premium',category:'Sushi',description:'8 Stück mit Philadelphia und speziellen Soßen',items:[
  {name:'Veggie Queen',price:12,description:'Gurke, Rettich, Rucola, Avocado, Sesam'},
  {name:'Enjoy Aroma',price:12.9,description:'Lachs, Avocado, Gurke, flambierter Lachs, Sesam'},
  {name:'Honeymoon',price:15,description:'Lachs, Avocado, Gurke, Lachstatar, Masago'},
  {name:'Try It Now',price:15,description:'Thunfisch, Avocado, Gurke, Thunfischtatar, Masago'},
  {name:'The Passion',price:15,description:'Lachs, Avocado, Gurke, Thunfisch, Chili'},
  {name:'Mizu Premium',price:15,description:'Gegrillter Lachs, Avocado, Lachstatar, Sesam'},
  {name:'Lady Eye',price:15,description:'Ebi Tempura, Masago, Gurke, Avocado'},
  {name:'Royal Art',price:18,description:'Lachs, Avocado, Gurke, flambierter Aal, Sesam, Lachskaviar'},
 ]},
 {title:'Inside Out Sushi',category:'Sushi',items:[
  {name:'Sake I.O.',price:9,description:'Lachs, Avocado'},
  {name:'Sake Yaki I.O.',price:9,description:'Gegrillter Lachs, Avocado'},
  {name:'Tuna I.O.',price:10,description:'Thunfisch, Avocado'},
  {name:'Chicken I.O.',price:8.5,description:'Hühnerfleisch, Avocado, Gurke'},
  {name:'California I.O.',price:8,description:'Krebsfleischimitat'},
  {name:'Unagi I.O.',price:10,description:'Gegrillter Aal'},
  {name:'Yasai I.O.',price:8,description:'Eingelegter Rettich, Rucola, Avocado, Gurke'},
  {name:'Ebi I.O.',price:8.5,description:'Garnelen-Tempura, Avocado'},
 ]},
 {title:'Baked Sushi',category:'Sushi',items:[
  {name:'Mr. Tokio Tofu',price:12,description:'Tofu, Rettich'},
  {name:'Mr. Tokio Vegan',price:12,description:'Süßkartoffeln, Rettich'},
  {name:'Holiday Roll',price:12,description:'Krebsfleischimitat'},
  {name:'Tokio Dreams',price:12.9,description:'Lachs'},
  {name:'Lucky Lady',price:15,description:'Thunfisch'},
  {name:'Mizu Love',price:12.9,description:'Garnelen'},
  {name:'Mr. Beef',price:13.8,description:'Rinderfilet, Chili, Pfeffer'},
  {name:'Have Fun',price:16.8,description:'Aal'},
 ]},
 {title:'Desserts',category:'Desserts',items:[
  {name:'Baked Pineapple',price:5,description:'Gebackene Ananas, Honig, Erdnüsse'},
  {name:'Baked Banana',price:5,description:'Gebackene Banane, Honig, Erdnüsse'},
  {name:'Mochi Kuchen',price:4,description:'Klebreisteig · Matcha, Kokos, Mango oder Taro'},
 ]},
 {title:'Softdrinks',category:'Getränke',items:variants(['Cola','Cola Zero','Fanta','Sprite','Mineralwasser','Stillwasser'],[2.8,2.8,2.8,2.8,2.8,2.8])},
 {title:'Tee',category:'Getränke',items:[
  {name:'Frischer Ingwertee',price:3.6},{name:'Jasmintee',price:3.6},
  {name:'Verschiedene Tees',price:2.8,description:'Pfefferminztee, Früchtetee oder schwarzer Tee'},
  {name:'Grüner Tee',price:3.6},
 ]},
 {title:'Kaffee & Kakao',category:'Getränke',items:[
  ...variants(['Kaffee','Espresso','Cappuccino','Heißer Kakao'],[3,3,3,3]),
  {name:'Eisschokolade',price:5,description:'Schokolade mit Sahne'},
  {name:'Eiskaffee',description:'Kaffee, Kondensmilch, Sahne, Eiswürfel'},
 ]},
 {title:'Roséwein',category:'Getränke',items:[{name:'Pueblo Viejo',price:5.5,description:'Trocken · Spanien · 14,5 % vol.'}]},
 {title:'Sonstiges',category:'Nudeln & Bowls',items:[
  {name:'Rice Noodle Salad',description:'Reisnudeln mit Gartensalat, Kräutern, Erdnüssen und Sesamdressing'},
  {name:'Frühlingsrollen',price:16},
 ]},
];